### ISSUE TITLE
Incompatible with gym 0.10.9

### ISSUE THREAD

**Issue by ForrestCKoch** [Kautenja/gym-tetris#11]
Hi,

I seem to be unable to make your environment in gym-0.10.9. Any ideas as to how I might fix this?

```
Python 3.6.6 (default, Nov 13 2018, 08:06:02) 
[GCC 8.2.1 20180831] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import gym_tetris
pygame 1.9.4
Hello from the pygame community. https://www.pygame.org/contribute.html
>>> env = gym_tetris.make('Tetris-v0')
/usr/lib/python3.6/site-packages/gym/envs/registration.py:14: PkgResourcesDeprecationWarning: Parameters to load are deprecated.  Call .resolve and .require separately.
  result = entry_point.load(False)
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/usr/lib/python3.6/site-packages/gym_tetris/_registration.py", line 18, in make
    return gym.make(environment)
  File "/usr/lib/python3.6/site-packages/gym/envs/registration.py", line 167, in make
    return registry.make(id)
  File "/usr/lib/python3.6/site-packages/gym/envs/registration.py", line 119, in make
    env = spec.make()
  File "/usr/lib/python3.6/site-packages/gym/envs/registration.py", line 86, in make
    env = cls(**self._kwargs)
  File "/usr/lib/python3.6/site-packages/gym_tetris/tetris_env.py", line 35, in __init__
    self.observation_space = gym.spaces.Box(
AttributeError: module 'gym' has no attribute 'spaces
```

**Comment by Kautenja** [comment]
hmm. looks like despite 0.10.9 being a minor update from 0.10.5, gym has made some API breaking changes. Downgrading gym to 0.10.5 should resolve your problem. The codebase will need updated to fit the new gym API

**Comment by ForrestCKoch** [comment]
Sorry for the delayed response.

Downgrading to 0.10.5 does fix this.

**Comment by Kautenja** [comment]
closing issue.
