### ISSUE TITLE
can't get example code from documentation to run

### ISSUE THREAD

**Issue by pthornton614** [Kautenja/gym-tetris#23]
Installed the library, was able to run the single player one liner.  Tried making a py file with the example code, and getting the error below.

Example code, ive named testGym.py:
  GNU nano 4.8                       testGym.py                                 
from nes_py.wrappers import JoypadSpace
import gym_tetris
from gym_tetris.actions import MOVEMENT

env = gym_tetris.make('Tetris-v0')
env = JoypadSpace(env, MOVEMENT)

done = True
for step in range(5000):
    if done:
        state = env.reset()
    state, reward, done, info = env.step(env.action_space.sample())
    env.render()

env.close()

____________________________________________________-
error i receive:

(base) peter@peter-VirtualBox:~/TetrisAIProject$ python testGym.py
Traceback (most recent call last):
  File "/home/peter/conda3/lib/python3.7/site-packages/gym/envs/registration.py", line 121, in spec
    return self.env_specs[id]
KeyError: 'Tetris-v0'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "testGym.py", line 5, in <module>
    env = gym_tetris.make('Tetris-v0')
  File "/home/peter/conda3/lib/python3.7/site-packages/gym/envs/registration.py", line 145, in make
    return registry.make(id, **kwargs)
  File "/home/peter/conda3/lib/python3.7/site-packages/gym/envs/registration.py", line 89, in make
    spec = self.spec(path)
  File "/home/peter/conda3/lib/python3.7/site-packages/gym/envs/registration.py", line 131, in spec
    raise error.UnregisteredEnv('No registered env with id: {}'.format(id))
gym.error.UnregisteredEnv: No registered env with id: Tetris-v0
(base) peter@peter-VirtualBox:~/TetrisAIProject$ testGym.py
testGym.py: command not found

**Comment by Kautenja** [comment]
Closing this out as fixed on `master`.

The original problem was tied to the old example and environment ID. The repo now documents and registers the Gymnasium-native environments as `TetrisA-v0` / `TetrisB-v0`, and the current usage flow is:

```python
import gymnasium as gym
import gym_tetris

env = gym.make('TetrisA-v0', render_mode='rgb_array')
```

I also verified locally that `import gym_tetris`, `gym.make('TetrisA-v0', render_mode='rgb_array')`, `reset(seed=123)`, and `step(...)` all work successfully against the current code. This landed as part of the Gymnasium migration in `d77063a`, which is on `master` via PR #28.

Thanks for reporting this.
